server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recommend_system?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    druid:
#      initial-size: 5 #连接池初始大小
#      min-idle: 10
#      max-active: 20
#      web-stat-filter:
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      stat-view-servlet:
#        login-username: druid
#        login-password: druid
mybatis:
  type-aliases-package: com.zachcc.mbg.entities
  mapper-locations: classpath:mapper/*.xml